### ISSUE TITLE
Location tracking

### ISSUE THREAD

**Issue by tirth-clearsense** [vaibhav-clearsense/personicle-react-application#1]
- [x] The app should track continuous device location (foreground/background/killed) if permission is granted by user.
- [x] Sync location data to Personicle write api
- [x] Able to send locations batch from native sqlite db once connected to network

**Comment by tirth-clearsense** [comment]
fix by [commit](https://github.com/vaibhav-clearsense/personicle-react-application/commit/8f4766c96a81f585a61660b9cff7d76b4ebbdca3)
